# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 950eff60eb854dbabce1363fbd6dce4fe691136f9802db3be60a15adeae8cd6872a3e49e42c7daf69054175d5e643ffe2398e784669596731d3ca2bae273805a

test:
  secret_key_base: b3d55def252ed6296a075bc456451fc6f1beed5961587c0bc9b67bf2f0e54fd1f5739786ddb2440a4c90636bf7c56816b35571d711cf86c9d4ab8e6de6c86688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
